version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages
        description: "Raw Telegram messages scraped from medical channels"
        columns:
          - name: message_id
            description: "Unique identifier for each message"
            tests:
              - unique
              - not_null
          - name: channel_name
            description: "Name of the Telegram channel"
          - name: message_date
            description: "Timestamp when message was posted"
          - name: message_text
            description: "Content of the message"
          - name: has_media
            description: "Whether the message contains media"
          - name: image_path
            description: "Path to downloaded image file"
          - name: views
            description: "Number of views on the message"
          - name: forwards
            description: "Number of times message was forwarded"
